/*
 * Copyright Cedar Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! Contains utilities for accessing integration and corpus tests files.

use std::path::{Path, PathBuf};
use walkdir::WalkDir;

use crate::integration_testing::resolve_integration_test_path;

/// Path of the folder containing the (handwritten) integration tests
fn integration_test_folder() -> &'static Path {
    Path::new("tests")
}

/// Path of the folder containing the autogenerated corpus tests
fn corpus_test_folder() -> &'static Path {
    Path::new("corpus-tests")
}

/// Iterate over tests in the integration tests folder.
pub fn get_integration_tests() -> impl Iterator<Item = PathBuf> {
    let tests_folder = resolve_integration_test_path(integration_test_folder());
    // find all `*.json` files in the integration tests folder
    WalkDir::new(&tests_folder)
        .into_iter()
        .map(|e| e.expect("failed to access file in tests").into_path())
        // ignore non-JSON files (and directories, which don't have an extension)
        .filter(|p| {
            p.extension()
                .map(|ext| ext.eq_ignore_ascii_case("json"))
                .unwrap_or(false)
        })
}

/// Iterate over (a subset of) tests in the corpus tests folder. The `prefix`
/// argument is used to limit the iterator to only tests starting with that
/// prefix. Pass an empty prefix to iterate over all test.
pub fn get_corpus_tests(prefix: &str) -> impl Iterator<Item = PathBuf> + '_ {
    let tests_folder = resolve_integration_test_path(corpus_test_folder());
    WalkDir::new(&tests_folder)
        .into_iter()
        .map(|e| {
            e.expect("failed to access file in corpus_tests. Maybe you haven't unpacked `corpus-tests.tar.gz`")
                .into_path()
        })
        .filter(move |p| {
            let filename = p
                .file_name()
                .expect("didn't expect subdirectories in corpus-tests")
                .to_str()
                .expect("expected filenames to be valid UTF-8");
            filename.starts_with(prefix) && filename.ends_with(".json") && !filename.ends_with(".entities.json")
        })
}
