# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    # Update all explicitly defined dependencies
    allow:
      - dependency-type: "all"
    ignore:
      # Due to a build error when updating from tsify 0.4.5, we are skipping the
      # next release (0.5.5). Issue #1744 tracks an eventual upgrade to this
      # version or a later version.
      - dependency-name: "tsify"
        versions: ["0.5.5"]
    # Group all updates into one pull request
    groups:
      rust-dependencies:
        patterns:
          - "*"
