name: Request for Comments (RFC)
description: Gather community feedback regarding a proposed change to the Cedar language
labels: feature-request

body:
  - type: markdown
    attributes:
      value: |
        This is a Request For Comments (RFC). It is intended to elicit community feedback regarding a proposed change to the language. Please feel free to post comments or questions here.

  - type: textarea
    attributes:
      label: Summary
      description: In one or two sentences, why should this change exist?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivation
      description: Why is this RFC needed? What will happen if accepted? What wil happen if it is not accepted?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Basic Example
      description: Please include an example of your new feature. 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Formalism 
      description: Provide details on how the our formalisms of the language will need to change. Formalisms include the formal grammar, the dafny spec of the interpreter, and the Dafny models of the interpreter and the validator.


  - type: textarea
    attributes:
      label: Detailed Design
      description: Provide enough detail on _how_ this should be implemented such that someone other than yourself could build it. 
    validations:
      required: true

  - type: textarea
    attributes:
      label: Correctness
      description: Provide details on how we will test and verify correctness of the proposed change.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Drawbacks
      description: Is this a breaking change? Days/Weeks/Months to implement? Will it require extensive documentation & examples?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Adoption Strategy
      description: What supporting efforts will be needed (e.g. documentation, tests, tutorials, public outreach, etc.)?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Related Issues
      description: Add Github issue numbers/URLs that informed or would be impacted by this proposal.

  - type: textarea
    attributes:
      label: References
      description: List articles, resources, prior art, and inspiration for this proposal.


