name: Comment on the pull request
permissions:
  contents: read
  pull-requests: write
  actions: read
  statuses: read
on:
  workflow_run:
    workflows: [Cargo Build & Test]
    types:
      - completed

jobs:
  post_comment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: 3.14
      - name: Create and post the comment
        env:
          RUN_ID: ${{github.event.workflow_run.id }}
          GH_TOKEN: ${{ github.token }}
          PR_TARGET_REPO: ${{ github.repository }}
          HEAD_SHA: ${{ github.event.workflow_run.head_sha}}
          # If the PR is from a fork, prefix the branch with `<owner-login>:`, otherwise only the PR branch name should be used:
          PR_BRANCH: |-
            ${{
              (github.event.workflow_run.head_repository.owner.login != github.event.workflow_run.repository.owner.login)
                && format('{0}:{1}', github.event.workflow_run.head_repository.owner.login, github.event.workflow_run.head_branch)
                || github.event.workflow_run.head_branch
            }}
          COMMENT_FILE: comment.md
        shell: bash
        run: |
          # Download coverage data for the run. Exit early if the data is not found.
          gh run download "${RUN_ID}" --name coverage_data --dir coverage_data || exit 0

          # Find the number and base SHA of the PR that should be commented on.
          PR_NUMBER=$(gh pr view --repo "${PR_TARGET_REPO}" --json 'number' --jq '.number' -- "${PR_BRANCH}")
          BASE_SHA=$(gh pr view --repo "${PR_TARGET_REPO}" --json 'baseRefOid' --jq '.baseRefOid' -- "${PR_BRANCH}")

          # Find the identifier of the artifact with the name "coverage_report_html" written by the triggering workflow run.
          ARTIFACT_ID=$(gh api "repos/${PR_TARGET_REPO}/actions/runs/${RUN_ID}/artifacts" --jq '.artifacts[] | select(.name=="coverage_report_html") | .id')
          REPORT_URL="https://github.com/${PR_TARGET_REPO}/actions/runs/${RUN_ID}/artifacts/${ARTIFACT_ID}"

          python .github/scripts/create_comment.py \
            --coverage_json coverage_data/coverage.json \
            --output-file "${COMMENT_FILE}" \
            --head-sha "${HEAD_SHA}" \
            --base-sha "${BASE_SHA}" \
            --report-url "${REPORT_URL}"
          gh pr comment "${PR_NUMBER}" --body-file "${COMMENT_FILE}"
  
