name: Nightly Build Downstream Dependencies
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
env: 
  CARGO_TERM_COLOR: always
jobs:
  build-cedar-java:
    uses: cedar-policy/cedar-java/.github/workflows/run_cedar_java_reusable.yml@main
    with:
      # The fully-formed ref of the branch or tag that triggered the workflow run.
      cedar_policy_ref: ${{ github.ref }}
      # Since this workflow is not triggered by pull request events, 
      # this will be the short ref name of the branch or tag that triggered the workflow run.
      # For more information see: https://docs.github.com/en/actions/reference/workflows-and-actions/contexts#github-context
      cedar_java_ref: ${{ github.ref_name }} 
