# Note: This workflow can only be run from the 'main' branch to
# ensure that the latest version of this workflow is used.
# However, the release will not necessarily be performed from the 'main' branch
# as the input `tag` is used to determine which GitHub tag will be checked out for the release.
name: Publish base Cedar crates to crates.io
on:
    workflow_dispatch:
        inputs:
            tag:
                required: true
                type: string
                description: "The GitHub tag to be released. Must be of the form 'v<MAJOR>.<MINOR>.<PATCH>'"

# Declare default permissions as read only.
permissions: read-all

jobs:
    publish:
        uses: ./.github/workflows/publish_reusable.yml
        permissions:
            contents: read
            id-token: write
        with:
            tag: ${{ inputs.tag }}
            tag_prefix: "v"
            version_toml_path: "Cargo.toml"
            version_toml_key: "workspace.package.version"
            # Order matters: dependencies must be listed before dependents.
            # cedar-policy-validator no longer exists on main but is kept for older release branches.
            publish_packages: "cedar-policy-core cedar-policy-validator cedar-policy-formatter cedar-policy"
