/*
 * Copyright Cedar Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! Error types for the Cedar entity data syntax parser

use std::{
    collections::{HashMap, HashSet},
    fmt::Display,
    iter::{Chain, Once},
    sync::{Arc, LazyLock},
    vec,
};

use crate::ast::AnyId;
use crate::parser::{
    err::{expected_to_string, ExpectedTokenConfig},
    unescape::UnescapeError,
    Node,
};
use lalrpop_util as lalr;
use miette::{Diagnostic, LabeledSpan, SourceSpan};
use nonempty::NonEmpty;
use smol_str::SmolStr;
use thiserror::Error;

/// User errors that can be raised from within grammar actions
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum UserError {
    /// Invalid escape codes in string literal
    #[error("Invalid escape codes")]
    StringEscape(Node<NonEmpty<UnescapeError>>),
    /// Integer overflow
    #[error("integer literal `{0}` is too large")]
    IntegerOverflow(SmolStr, Node<()>),
    /// Duplicate annotations
    #[error("duplicate annotations: `{0}`")]
    DuplicateAnnotations(AnyId, Node<()>, Node<()>),
}

impl UserError {
    /// Extract a primary source span locating the error.
    pub(crate) fn primary_source_span(&self) -> Option<SourceSpan> {
        match self {
            Self::StringEscape(n) => n.loc.as_ref().map(|loc| loc.span),
            Self::IntegerOverflow(_, n) => n.loc.as_ref().map(|loc| loc.span),
            Self::DuplicateAnnotations(_, n, _) => n.loc.as_ref().map(|loc| loc.span),
        }
    }
}

pub(crate) type RawLocation = usize;
pub(crate) type RawToken<'a> = lalr::lexer::Token<'a>;

pub(crate) type RawParseError<'a> = lalr::ParseError<RawLocation, RawToken<'a>, UserError>;
pub(crate) type RawErrorRecovery<'a> = lalr::ErrorRecovery<RawLocation, RawToken<'a>, UserError>;

type OwnedRawParseError = lalr::ParseError<RawLocation, String, UserError>;

static ENTITY_DATA_TOKEN_CONFIG: LazyLock<ExpectedTokenConfig> =
    LazyLock::new(|| ExpectedTokenConfig {
        friendly_token_names: HashMap::from([
            ("NAMESPACE", "`namespace`"),
            ("INSTANCE", "`instance`"),
            ("IN", "`in`"),
            ("TAGS", "`tags`"),
            ("TRUE", "`true`"),
            ("FALSE", "`false`"),
            ("IDENTIFIER", "identifier"),
            ("NUMBER", "integer literal"),
            ("STRINGLIT", "string literal"),
        ]),
        impossible_tokens: HashSet::new(),
        special_identifier_tokens: HashSet::from(["NAMESPACE", "INSTANCE", "IN", "TAGS"]),
        identifier_sentinel: "IDENTIFIER",
        first_set_identifier_tokens: HashSet::new(),
        first_set_sentinel: "\"{\"",
    });

/// A single parse error for entity data syntax
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ParseError {
    /// Error generated by lalrpop
    pub(crate) err: OwnedRawParseError,
    /// Source code
    src: Arc<str>,
}

impl ParseError {
    pub(crate) fn from_raw_parse_error(err: RawParseError<'_>, src: Arc<str>) -> Self {
        Self {
            err: err.map_token(|token| token.to_string()),
            src,
        }
    }

    pub(crate) fn from_raw_error_recovery(recovery: RawErrorRecovery<'_>, src: Arc<str>) -> Self {
        Self::from_raw_parse_error(recovery.error, src)
    }

    /// Extract a primary source span locating the error.
    pub fn primary_source_span(&self) -> Option<SourceSpan> {
        match &self.err {
            OwnedRawParseError::InvalidToken { location } => Some(SourceSpan::from(*location)),
            OwnedRawParseError::UnrecognizedEof { location, .. } => {
                Some(SourceSpan::from(*location))
            }
            OwnedRawParseError::UnrecognizedToken {
                token: (token_start, _, token_end),
                ..
            } => Some(SourceSpan::from(*token_start..*token_end)),
            OwnedRawParseError::ExtraToken {
                token: (token_start, _, token_end),
            } => Some(SourceSpan::from(*token_start..*token_end)),
            OwnedRawParseError::User { error } => error.primary_source_span(),
        }
    }
}

impl Display for ParseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let Self { err, .. } = self;
        match err {
            OwnedRawParseError::InvalidToken { .. } => write!(f, "invalid token"),
            OwnedRawParseError::UnrecognizedEof { .. } => write!(f, "unexpected end of input"),
            OwnedRawParseError::UnrecognizedToken {
                token: (_, token, _),
                ..
            } => write!(f, "unexpected token `{token}`"),
            OwnedRawParseError::ExtraToken {
                token: (_, token, _),
                ..
            } => write!(f, "extra token `{token}`"),
            OwnedRawParseError::User { error } => write!(f, "{error}"),
        }
    }
}

impl std::error::Error for ParseError {}

impl Diagnostic for ParseError {
    fn source_code(&self) -> Option<&dyn miette::SourceCode> {
        Some(&self.src as &dyn miette::SourceCode)
    }

    fn labels(&self) -> Option<Box<dyn Iterator<Item = LabeledSpan> + '_>> {
        let primary_source_span = self.primary_source_span();
        match &self.err {
            OwnedRawParseError::InvalidToken { .. } => primary_source_span
                .map(|span| Box::new(std::iter::once(LabeledSpan::underline(span))) as _),
            OwnedRawParseError::UnrecognizedEof { expected, .. } => {
                primary_source_span.map(|span| {
                    Box::new(std::iter::once(LabeledSpan::new_with_span(
                        expected_to_string(expected, &ENTITY_DATA_TOKEN_CONFIG),
                        span,
                    ))) as _
                })
            }
            OwnedRawParseError::UnrecognizedToken { expected, .. } => {
                primary_source_span.map(|span| {
                    Box::new(std::iter::once(LabeledSpan::new_with_span(
                        expected_to_string(expected, &ENTITY_DATA_TOKEN_CONFIG),
                        span,
                    ))) as _
                })
            }
            OwnedRawParseError::ExtraToken { .. } => primary_source_span
                .map(|span| Box::new(std::iter::once(LabeledSpan::underline(span))) as _),
            OwnedRawParseError::User { .. } => primary_source_span
                .map(|span| Box::new(std::iter::once(LabeledSpan::underline(span))) as _),
        }
    }
}

/// Multiple parse errors
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ParseErrors(pub(crate) Box<NonEmpty<ParseError>>);

impl ParseErrors {
    /// Create a new `ParseErrors` from a first error and additional errors
    pub fn new(first: ParseError, tail: impl IntoIterator<Item = ParseError>) -> Self {
        Self(Box::new(NonEmpty {
            head: first,
            tail: tail.into_iter().collect(),
        }))
    }

    /// Try to create `ParseErrors` from an iterator; returns `None` if empty
    pub fn from_iter(i: impl IntoIterator<Item = ParseError>) -> Option<Self> {
        let v = i.into_iter().collect::<Vec<_>>();
        Some(Self(Box::new(NonEmpty::from_vec(v)?)))
    }

    /// Borrowed Iterator over reported errors
    pub fn iter(&self) -> impl Iterator<Item = &ParseError> {
        self.0.iter()
    }
}

impl Display for ParseErrors {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0.first())
    }
}

impl IntoIterator for ParseErrors {
    type Item = ParseError;
    type IntoIter = Chain<Once<ParseError>, vec::IntoIter<ParseError>>;

    fn into_iter(self) -> Self::IntoIter {
        self.0.into_iter()
    }
}

impl std::error::Error for ParseErrors {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        std::error::Error::source(self.0.first())
    }
}

impl Diagnostic for ParseErrors {
    fn related<'a>(&'a self) -> Option<Box<dyn Iterator<Item = &'a dyn Diagnostic> + 'a>> {
        let mut errs = self.iter().map(|err| err as &dyn Diagnostic);
        errs.next().map(move |first_err| match first_err.related() {
            Some(first_err_related) => Box::new(first_err_related.chain(errs)),
            None => Box::new(errs) as Box<dyn Iterator<Item = _>>,
        })
    }

    fn code<'a>(&'a self) -> Option<Box<dyn Display + 'a>> {
        Diagnostic::code(self.0.first())
    }

    fn severity(&self) -> Option<miette::Severity> {
        Diagnostic::severity(self.0.first())
    }

    fn help<'a>(&'a self) -> Option<Box<dyn Display + 'a>> {
        Diagnostic::help(self.0.first())
    }

    fn url<'a>(&'a self) -> Option<Box<dyn Display + 'a>> {
        Diagnostic::url(self.0.first())
    }

    fn source_code(&self) -> Option<&dyn miette::SourceCode> {
        Diagnostic::source_code(self.0.first())
    }

    fn labels(&self) -> Option<Box<dyn Iterator<Item = LabeledSpan> + '_>> {
        Diagnostic::labels(self.0.first())
    }

    fn diagnostic_source(&self) -> Option<&dyn Diagnostic> {
        Diagnostic::diagnostic_source(self.0.first())
    }
}

/// Errors during AST → Entities conversion
#[derive(Debug, Diagnostic, Error)]
#[non_exhaustive]
pub enum ConversionError {
    /// Unknown extension function
    #[error("unknown extension function `{name}`")]
    UnknownExtensionFunction {
        /// The function name
        name: String,
    },

    /// Unresolved entity type
    #[error("could not resolve entity type `{name}`")]
    UnresolvedType {
        /// The unresolved type name
        name: String,
    },

    /// Duplicate key in a record
    #[error("duplicate key `{key}` in record")]
    DuplicateRecordKey {
        /// The duplicated key
        key: String,
    },

    /// Error evaluating an entity's attributes or tags, such as an unknown
    /// extension function or a wrong number of arguments to one. Wraps the
    /// underlying [`EntityAttrEvaluationError`] so its entity/attribute context
    /// and diagnostic are preserved.
    #[error(transparent)]
    #[diagnostic(transparent)]
    EntityAttributeEvaluation(#[from] crate::ast::EntityAttrEvaluationError),
}

/// A collection of conversion errors.
///
/// Invariant: constructed only via [`ConversionErrors::new`] with a non-empty
/// `Vec`, so [`ConversionErrors::first`] always returns `Some`.
#[derive(Debug, Error)]
pub struct ConversionErrors(pub(crate) Vec<ConversionError>);

impl ConversionErrors {
    /// Create from a vec of errors (must be non-empty)
    pub fn new(errors: Vec<ConversionError>) -> Self {
        Self(errors)
    }

    /// Iterate over the errors
    pub fn iter(&self) -> impl Iterator<Item = &ConversionError> {
        self.0.iter()
    }

    /// The first (primary) error. Always `Some` given the non-empty invariant.
    fn first(&self) -> Option<&ConversionError> {
        self.0.first()
    }
}

// Delegate the message and diagnostic to the primary (first) error, and expose
// any remaining errors as `related` diagnostics, rather than reporting only a
// count.
impl Display for ConversionErrors {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self.first() {
            Some(first) => write!(f, "{first}"),
            // Unreachable given the non-empty invariant, but avoid panicking.
            None => write!(f, "entity data conversion failed"),
        }
    }
}

impl Diagnostic for ConversionErrors {
    fn related<'a>(&'a self) -> Option<Box<dyn Iterator<Item = &'a dyn Diagnostic> + 'a>> {
        // Expose the 2nd..Nth errors as related diagnostics (the 1st is the
        // primary, surfaced via the delegated methods below).
        let mut errs = self
            .0
            .iter()
            .skip(1)
            .map(|err| err as &dyn Diagnostic)
            .peekable();
        if errs.peek().is_none() {
            None
        } else {
            Some(Box::new(errs))
        }
    }

    fn code<'a>(&'a self) -> Option<Box<dyn Display + 'a>> {
        self.first().and_then(Diagnostic::code)
    }

    fn severity(&self) -> Option<miette::Severity> {
        self.first().and_then(Diagnostic::severity)
    }

    fn help<'a>(&'a self) -> Option<Box<dyn Display + 'a>> {
        self.first().and_then(Diagnostic::help)
    }

    fn url<'a>(&'a self) -> Option<Box<dyn Display + 'a>> {
        self.first().and_then(Diagnostic::url)
    }

    fn source_code(&self) -> Option<&dyn miette::SourceCode> {
        self.first().and_then(Diagnostic::source_code)
    }

    fn labels(&self) -> Option<Box<dyn Iterator<Item = LabeledSpan> + '_>> {
        self.first().and_then(Diagnostic::labels)
    }

    fn diagnostic_source(&self) -> Option<&dyn Diagnostic> {
        self.first().and_then(Diagnostic::diagnostic_source)
    }
}

/// Top-level error for parsing Cedar entity data syntax
#[derive(Debug, Diagnostic, Error)]
#[non_exhaustive]
pub enum CedarEntitiesError {
    /// Syntax error during parsing
    #[error(transparent)]
    #[diagnostic(transparent)]
    SyntaxError(#[from] ParseErrors),

    /// Error during AST → Entities conversion
    #[error(transparent)]
    #[diagnostic(transparent)]
    ConversionError(#[from] ConversionErrors),
}
